Check for script `BIN_REQUIRES`

diff --git a/strategy/debian-udd/bin/db-dump-restore b/strategy/debian-udd/bin/db-dump-restore
--- a/strategy/debian-udd/bin/db-dump-restore
+++ b/strategy/debian-udd/bin/db-dump-restore
@@ -7,8 +7,26 @@ set -euo pipefail
 DB_USER="${PGUSER:-postgres}"
 DB_NAME="${DEBIAN_UDD_PGDATABASE:-udd}"
 
+## Requires
+BIN_REQUIRES='
+	grep
+	cat
+	seq
+
+	apt-get
+	dpkg-query
+
+	psql
+	pg_isready
+	pg_restore
+'
+for CHECK_BIN in $BIN_REQUIRES ; do
+	type -P $CHECK_BIN >/dev/null || ( echo "$0: Could not find $CHECK_BIN" && false )
+done
+
 
 _check_dbname() {
+	## Requires: grep
 	if echo "$DB_NAME" | grep -qF '"'; then
 		# Double quotes would have to be escaped by doubling the
 		# character (e.g., "one""two").
@@ -19,6 +37,7 @@ _check_dbname() {
 
 
 create_database() {
+	## Requires: cat psql
 	echo "Creating database '$DB_NAME'" >&2
 
 	export CREATE_DATABASE="$(cat <<EOF
@@ -42,6 +61,7 @@ EOF
 }
 
 install_extensions() {
+	## Requires: apt-get dpkg-query
 	if [ -z "$PG_MAJOR" ]; then
 		echo "Must set PG_MAJOR" >&2
 		exit 1
@@ -60,6 +80,7 @@ install_extensions() {
 }
 
 restore_database() {
+	## Requires: psql pg_restore
 	local DUMP_FILE="$1"
 
 	echo 'CREATE EXTENSION debversion' \
@@ -81,6 +102,7 @@ restore_database() {
 }
 
 main() {
+	## Requires: pg_isready psql
 	_check_dbname
 
 	PG_ISREADY=''
